# Generated by Django 5.1.3 on 2024-11-09 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, unique=True)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.marka')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('millage', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('color', models.CharField(choices=[('КРАСНЫЙ', 'Красный'), ('СИНИЙ', 'Синий'), ('ЖЕЛНЫЙ', 'Желтый'), ('ЧЕРНЫЙ', 'Черный')], default='ЧЕРНЫЙ', max_length=9)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('have', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('video', models.FileField(blank=True, null=True, upload_to='img/')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carmodel')),
                ('car_marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.marka')),
            ],
        ),
    ]
